# Generated by Django 5.1.5 on 2025-01-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, help_text='Тут нужно писать общее кол-во товаров', verbose_name='Количество товаров'),
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default=1, help_text='Тут нужно писать артикул товара (номер)', max_length=11, verbose_name='Артикул товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, help_text='Тут нужно писать название бренда (ex: Lacoste)', max_length=100, verbose_name='Название бренда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.CharField(default=1, help_text='Тут нужно писать гарантию продукта', max_length=100, verbose_name='Гарантия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacture',
            field=models.TextField(default=1, help_text='Тут нужно писать где был произведен товар', verbose_name='Производство (чьё)'),
            preserve_default=False,
        ),
    ]
